import { createApp } from 'vue'
import App from './App.vue'
import router from '../src/route/route'
import Aura from '@primevue/themes/aura';
import ConfirmationService from 'primevue/confirmationservice';
import ToastService from 'primevue/toastservice';
import PrimeVue from 'primevue/config';
import Ripple from 'primevue/ripple';
import Chart from 'primevue/chart';
import Menu from 'primevue/menu';
import DataTable from 'primevue/datatable';
import Button from 'primevue/button';
import tooltipDirective from 'primevue/button';
import ConfirmPopup from 'primevue/confirmpopup';
import Drawer from 'primevue/drawer';
import InputText from 'primevue/inputtext';
import Column from 'primevue/column';
import SelectButton from 'primevue/selectbutton';
import Popover from 'primevue/popover';
import Dialog from 'primevue/dialog';
import StyleClass from 'primevue/styleclass';
import styleclassDirective from 'primevue/styleclass';
import Toast from 'primevue/toast';
import Rating from 'primevue/rating';
import Fluid from 'primevue/fluid';
import Select from 'primevue/select';
import Textarea from 'primevue/textarea';
import InputGroup from 'primevue/inputgroup';
import InputGroupAddon from 'primevue/inputgroupaddon';
import ToggleButton from 'primevue/togglebutton';
import TreeSelect from 'primevue/treeselect';
import MultiSelect from 'primevue/multiselect';
import Listbox from 'primevue/listbox';
import ToggleSwitch from 'primevue/toggleswitch';
import Checkbox from 'primevue/checkbox';
import RadioButton from 'primevue/radiobutton';
import Knob from 'primevue/knob';
import ColorPicker from 'primevue/colorpicker';
import Slider from 'primevue/slider';
import InputNumber from 'primevue/inputnumber';
import DatePicker from 'primevue/datepicker';
import AutoComplete from 'primevue/autocomplete';
import FloatLabel from 'primevue/floatlabel';
import IconField from 'primevue/iconfield';
import InputIcon from 'primevue/inputicon';
import SplitButton from 'primevue/splitbutton';
import ButtonGroup from 'primevue/buttongroup';
import ProgressBar from 'primevue/progressbar';
import Tag from 'primevue/tag';
import OrderList from 'primevue/orderlist';
import PickList from 'primevue/picklist';
import DataView from 'primevue/dataview';
import TreeTable from 'primevue/treetable';
import Tree from 'primevue/tree';
import Galleria from 'primevue/galleria';
import Image from 'primevue/image';
import Carousel from 'primevue/carousel';
import PanelMenu from 'primevue/panelmenu';
import MegaMenu from 'primevue/megamenu';
import ContextMenu from 'primevue/contextmenu';
import TieredMenu from 'primevue/tieredmenu';
import Tabs from 'primevue/tabs';
import TabList from 'primevue/tablist';
import Tab from 'primevue/tab';
import Stepper from 'primevue/stepper';
import StepList from 'primevue/steplist';
import Step from 'primevue/step';
import Breadcrumb from 'primevue/breadcrumb';
import Menubar from 'primevue/menubar';
import Message from 'primevue/message';
import FileUpload from 'primevue/fileupload';
import Card from 'primevue/card';
import Timeline from 'primevue/timeline';
import Skeleton from 'primevue/skeleton';
import Chip from 'primevue/chip';
import ScrollPanel from 'primevue/scrollpanel';
import ScrollTop from 'primevue/scrolltop';
import AvatarGroup from 'primevue/avatargroup';
import Avatar from 'primevue/avatar';
import OverlayBadge from 'primevue/overlaybadge';
import Badge from 'primevue/badge';
import Password from 'primevue/password';
import Toolbar from 'primevue/toolbar';
import Splitter from 'primevue/splitter';
import SplitterPanel from 'primevue/splitterpanel';
import AnimateOnScroll from 'primevue/animateonscroll';


import '../src/assets/styles.scss';
import '@/assets/tailwind.css';

// Define the app before using it
const app = createApp(App);

app.use(router);
app.use(PrimeVue, { 
    ripple: true,
    theme: {
        preset: Aura,
        options: {
            darkModeSelector: '.app-dark'
        }
    } 
});
app.use(ToastService);
app.use(ConfirmationService);
app.component('Chart', Chart);
app.component('Menu', Menu);
app.component('DataTable', DataTable);
app.component('Button', Button);
app.directive('tooltip', tooltipDirective);
app.component('ConfirmPopup', ConfirmPopup);
app.component('Drawer', Drawer);
app.component('InputText', InputText);
app.component('Column', Column);
app.component('SelectButton', SelectButton);
app.component('Popover', Popover);
app.component('Dialog', Dialog);
app.component('Toast', Toast);
app.component('Rating', Rating);
app.directive('styleclass', styleclassDirective);
app.component('StyleClass', StyleClass);
app.component('Select', Select);
app.component('Fluid', Fluid);
app.component('Textarea', Textarea);
app.component('InputGroup', InputGroup);
app.component('InputGroupAddon', InputGroupAddon);
app.component('ToggleButton', ToggleButton);
app.component('TreeSelect', TreeSelect);
app.component('MultiSelect', MultiSelect);
app.component('Listbox', Listbox);
app.component('ToggleSwitch', ToggleSwitch);
app.component('Checkbox', Checkbox);
app.component('RadioButton', RadioButton);
app.component('Knob', Knob);
app.component('ColorPicker', ColorPicker);
app.component('Slider', Slider);
app.component('InputNumber', InputNumber);
app.component('DatePicker', DatePicker);
app.component('AutoComplete', AutoComplete);
app.component('FloatLabel', FloatLabel);
app.component('IconField', IconField);
app.component('InputIcon', InputIcon);
app.component('SplitButton', SplitButton);
app.component('ButtonGroup', ButtonGroup);
app.component('ProgressBar', ProgressBar);
app.component('OrderList', OrderList);
app.component('Tag', Tag);
app.component('PickList', PickList);
app.component('DataView', DataView);
app.component('TreeTable', TreeTable);
app.component('Tree', Tree);
app.component('Galleria', Galleria);
app.component('Image', Image);
app.component('Carousel', Carousel);
app.component('PanelMenu', PanelMenu);
app.component('MegaMenu', MegaMenu);
app.component('ContextMenu', ContextMenu);
app.component('TieredMenu', TieredMenu);
app.component('Tabs', Tabs);
app.component('TabList', TabList);
app.component('Tab', Tab);
app.component('Stepper', Stepper);
app.component('StepList', StepList);
app.component('Step', Step);
app.component('Breadcrumb', Breadcrumb);
app.component('Menubar', Menubar);
app.component('Message', Message);
app.component('FileUpload', FileUpload);
app.component('Card', Card);
app.component('Timeline', Timeline);
app.component('Skeleton', Skeleton);
app.component('Chip', Chip);
app.component('ScrollPanel', ScrollPanel);
app.component('ScrollTop', ScrollTop);
app.component('AvatarGroup', AvatarGroup);
app.component('Avatar', Avatar);
app.component('OverlayBadge', OverlayBadge);
app.component('Badge', Badge);
app.component('Password', Password);
app.component('Toolbar', Toolbar);
app.component('Splitter', Splitter);
app.component('SplitterPanel', SplitterPanel);
app.directive('Animateonscroll', AnimateOnScroll);
app.directive('ripple', Ripple);
app.mount('#app');
